name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  NUGET_REG: https://nuget.pkg.github.com/nowisys/index.json
  NUGET_KEY: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Pack
      run: dotnet pack --no-restore
    - name: Push
      run: dotnet nuget src/Hamster.Plugin/bin/Debug/Hamster.Plugin.*.nupgk --skip-dupicate -k ${{ env.NUGET_KEY }} -s ${{ env.NUGET_REG }}
