name: Release Build

on:
  release:
    types:
      - published

env:
  NUGET_REG: https://nuget.pkg.github.com/nowisys/index.json
  NUGET_KEY: ${{ secrets.NUGET_TOKEN }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Pack
      run: dotnet pack --no-restore
    - name: Publish
      run: dotnet publish
    - name: Zip Publish
      run: cd src/Hamster/bin/Debug/net5.0/publish && zip -r ../../../../../../hamster.zip ./* && cd -
    - name: upload
      env:
          GITHUB_TOKEN: ${{ env.NUGET_KEY }}
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./hamster.zip
        asset_name: hamster.zip
        asset_content_type: application/zip
    - name: Push
      run: dotnet nuget push src/Hamster.Plugin/bin/Debug/Hamster.Plugin.*.nupkg --skip-duplicate -k ${{ env.NUGET_KEY }} -s ${{ env.NUGET_REG }}
